# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-10 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hologram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('picture', models.ImageField(blank=True, upload_to='pictures')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('to_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
